config/routes.rb
Iconfs::Application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

  resources :schedules_events

  resources :days

  resources :tracks

  resources :rooms

  get 'admin/inipage'

  resources :pis

  resources :events

  resources :users do
    resources :notes, :controller => "notes"
    resources :favourites, :controller =>"favourites"
    resources :users_meetings, :controller => "users_meetings"
  end

  resources :documents
  resources :users_documents
  resources :schedules
  resources :meetings

  root :to => 'admin#inipage'

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :shared, :text, :title, :user_id, :updated_at

  belongs_to :user

  validates :title, :user_id, :presence=>true
  validates_uniqueness_of :user_id, :scope => :title

  def as_json(options={})
  super(
     :except => [:created_at]
  )
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  # GET /user/1/notes
  # GET /user/1/notes.json
  def index
    @user = User.find(params[:user_id])
    @notes = @user.notes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /user/1/notes/1
  # GET /user/1/notes/1.json
  def show
    @user = User.find(params[:user_id])
    @note = @user.notes.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /user/1/notes/new
  # GET /user/1/notes/new.json
  def new
    @user = User.find(params[:user_id])
    @note = @user.notes.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /user/1/notes/1/edit
  def edit
    @user = User.find(params[:user_id])
    @note = @user.notes.find(params[:id])
  end

  # POST /user/1/notes
  # POST /user/1/notes.json
  def create
    @user = User.find(params[:user_id])
    @note = @user.notes.create(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to [@user,@note], notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: [@user,@note] }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user/1/notes/1
  # PUT /user/1/notes/1.json
  def update
    @user = User.find(params[:user_id])
    @note = @user.notes.find(params[:id])
    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to [@user,@note], notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/1/notes/1
  # DELETE /user/1/notes/1.json
  def destroy
    @user = User.find(params[:user_id])
    @note = @user.notes.find(params[:id])
    @note.destroy
    respond_to do |format|
      format.html { redirect_to user_notes_path(@user) }
      format.json { head :no_content }
    end
  end

end

app/helpers/notes_helper.rb
module NotesHelper

end

app/views/notes/_form.html.erb
<%= form_for([@user, @note]) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :shared %><br />
    <%= f.check_box :shared %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', user_note_path(@user, @note) %> |
<%= link_to 'Back', user_notes_path(@user) %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<%= link_to 'New Note', new_user_note_path(@user) %>  || <%= link_to 'Back', user_path(@user) %>
<br />

<table>
  <tr>
    <th>Title</th>
    <th>Shared</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.title %></td>
    <td><%= note.shared %></td>
    <td><%= note.text %></td>
    <td><%= link_to 'Show', user_note_path(@user, note) %></td>
    <td><%= link_to 'Edit', edit_user_note_path(@user, note) %></td>
    <td><%= link_to 'Destroy', [@user, note], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', user_notes_path(@user) %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Shared:</b>
  <%= @note.shared %>
</p>

<p>
  <b>Text:</b>
  <%= @note.text %>
</p>


<%= link_to 'Edit', edit_user_note_path(@user, @note) %> |
<%= link_to 'Back', user_notes_path(@user) %>