config/routes.rb
Iconfs::Application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

  resources :schedules_events

  resources :days

  resources :tracks

  resources :rooms

  get 'admin/inipage'

  resources :pis

  resources :events

  resources :users do
    resources :notes, :controller => "notes"
    resources :favourites, :controller =>"favourites"
    resources :users_meetings, :controller => "users_meetings"
  end

  resources :documents
  resources :users_documents
  resources :schedules
  resources :meetings

  root :to => 'admin#inipage'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :local, :message, :time

  has_many :users, :through => :users_meetings

  validates :local, :presence => true
  validates :time, :presence => true

  def as_json(options={})
    super(
        :except => [:created_at, updated_at],
        include:{ users: { :only => [:name, :id, :photo_link] }}
    )
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to [@user,@meeting], notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: [@user,@meeting] }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to [@user,@meeting], notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to user_meetings_path(@user) }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<%= link_to 'New Meeting', new_meeting_path %> || <%= link_to 'Home', "/" %>
<br />

<table>
  <tr>
    <th>Time</th>
    <th>Local</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.time %></td>
    <td><%= meeting.local %></td>
    <td><%= meeting.message %></td>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time:</b>
  <%= @meeting.time %>
</p>

<p>
  <b>Local:</b>
  <%= @meeting.local %>
</p>

<p>
  <b>Message:</b>
  <%= @meeting.message %>
</p>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>