config/routes.rb
Iconfs::Application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

  resources :schedules_events

  resources :days

  resources :tracks

  resources :rooms

  get 'admin/inipage'

  resources :pis

  resources :events

  resources :users do
    resources :notes, :controller => "notes"
    resources :favourites, :controller =>"favourites"
    resources :users_meetings, :controller => "users_meetings"
  end

  resources :documents
  resources :users_documents
  resources :schedules
  resources :meetings

  root :to => 'admin#inipage'

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  attr_accessible :title, :document_id, :user_id

  belongs_to :user
  belongs_to :document

  validates :title, :presence => true
  validates :user_id, :presence => true
  validates :document_id, :presence => true

  # Each title appears only one time per user
  validates_uniqueness_of :title, :scope => :user_id

  # Each document appears only one time per user
  validates_uniqueness_of :document_id, :scope => :user_id

  def as_json(options={})
    super(
        :except => [:created_at,:updated_at, :document_id],
        include:{ document: {:except => [:id, :created_at, :user_id, :updated_at]}}
    )
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  # GET /favourites
  # GET /favourites.json
  def index
    @user = User.find(params[:user_id])
    @favourites = @user.favourites

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favourites }
    end
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @favourite }
    end
  end

  # GET /favourites/new
  # GET /favourites/new.json
  def new
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favourite }
    end
  end

  # GET /favourites/1/edit
  def edit
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])
  end

  # POST /favourites
  # POST /favourites.json
  def create
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.new(params[:favourite])

    respond_to do |format|
      if @favourite.save
        format.html { redirect_to [@user,@favourite], notice: 'Favourite was successfully created.' }
        format.json { render json: @favourite, status: :created, location: [@user,@favourite] }
      else
        format.html { render action: "new" }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /favourites/1
  # PUT /favourites/1.json
  def update
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])

    respond_to do |format|
      if @favourite.update_attributes(params[:favourite])
        format.html { redirect_to [@user,@favourite], notice: 'Favourite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @user = User.find(params[:user_id])
    @favourite = @user.favourites.find(params[:id])
    @favourite.destroy

    respond_to do |format|
      format.html { redirect_to user_favourites_path(@user) }
      format.json { head :no_content }
    end
  end

end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_form.html.erb
<%= form_for([@user,@favourite]) do |f| %>
  <% if @favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% @favourite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
   </div>

  <div class="field">
    <%= f.label :document_id %><br />
    <%= f.collection_select :document_id, Document.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing favourite</h1>

<%= render 'form' %>

<%= link_to 'Show', user_favourite_path(@user, @favourite) %> |
<%= link_to 'Back', user_favourites_path %>

app/views/favourites/index.html.erb
<h1>Listing favourites</h1>

<%= link_to 'New Favourite', new_user_favourite_path(@user) %> || <%= link_to 'Back', user_path(@user) %>

<br />

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favourites.each do |favourite| %>
  <tr>
    <td><%= link_to 'Show', user_favourite_path(@user, favourite) %></td>
    <td><%= link_to 'Edit', edit_user_favourite_path(@user, favourite) %></td>
    <td><%= link_to 'Destroy', [@user,favourite], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/favourites/new.html.erb
<h1>New favourite</h1>

<%= render 'form' %>

<%= link_to 'Back', user_favourites_path(@user) %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_favourite_path(@user,@favourite) %> |
<%= link_to 'Back', user_favourites_path(@user) %>