config/routes.rb
Iconfs::Application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

  resources :schedules_events

  resources :days

  resources :tracks

  resources :rooms

  get 'admin/inipage'

  resources :pis

  resources :events

  resources :users do
    resources :notes, :controller => "notes"
    resources :favourites, :controller =>"favourites"
    resources :users_meetings, :controller => "users_meetings"
  end

  resources :documents
  resources :users_documents
  resources :schedules
  resources :meetings

  root :to => 'admin#inipage'

end

app/models/users_document.rb
class UsersDocument < ActiveRecord::Base
  attr_accessible :document_id, :user_id

  belongs_to :document
  belongs_to :user

end

app/controllers/users_documents_controller.rb
class UsersDocumentsController < ApplicationController
  # GET /users_documents
  # GET /users_documents.json
  def index
    @users_documents = UsersDocument.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users_documents }
    end
  end

  # GET /users_documents/1
  # GET /users_documents/1.json
  def show
    @users_document = UsersDocument.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @users_document }
    end
  end

  # GET /users_documents/new
  # GET /users_documents/new.json
  def new
    @users_document = UsersDocument.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @users_document }
    end
  end

  # GET /users_documents/1/edit
  def edit
    @users_document = UsersDocument.find(params[:id])
  end

  # POST /users_documents
  # POST /users_documents.json
  def create
    @users_document = UsersDocument.new(params[:users_document])

    respond_to do |format|
      if @users_document.save
        format.html { redirect_to @users_document, notice: 'Users document was successfully created.' }
        format.json { render json: @users_document, status: :created, location: @users_document }
      else
        format.html { render action: "new" }
        format.json { render json: @users_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users_documents/1
  # PUT /users_documents/1.json
  def update
    @users_document = UsersDocument.find(params[:id])

    respond_to do |format|
      if @users_document.update_attributes(params[:users_document])
        format.html { redirect_to @users_document, notice: 'Users document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @users_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_documents/1
  # DELETE /users_documents/1.json
  def destroy
    @users_document = UsersDocument.find(params[:id])
    @users_document.destroy

    respond_to do |format|
      format.html { redirect_to users_documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_documents_helper.rb
module UsersDocumentsHelper
end

app/views/users_documents/_form.html.erb
<%= form_for(@users_document) do |f| %>
  <% if @users_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_document.errors.count, "error") %> prohibited this users_document from being saved:</h2>

      <ul>
      <% @users_document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_documents/edit.html.erb
<h1>Editing users_document</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_document %> |
<%= link_to 'Back', users_documents_path %>

app/views/users_documents/index.html.erb
<h1>Listing users_documents</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users_documents.each do |users_document| %>
  <tr>
    <td><%= link_to 'Show', users_document %></td>
    <td><%= link_to 'Edit', edit_users_document_path(users_document) %></td>
    <td><%= link_to 'Destroy', users_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Users document', new_users_document_path %>

app/views/users_documents/new.html.erb
<h1>New users_document</h1>

<%= render 'form' %>

<%= link_to 'Back', users_documents_path %>

app/views/users_documents/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_users_document_path(@users_document) %> |
<%= link_to 'Back', users_documents_path %>